//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.Persistence.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_locationWithPodV5
    {
        public int locationId { get; set; }
        public Nullable<int> parentId { get; set; }
        public string locationName { get; set; }
        public string building { get; set; }
        public int podId { get; set; }
        public string podName { get; set; }
        public string NTP_Server { get; set; }
        public string timezone { get; set; }
    }
}
